import { ViewConfig, ComponentNode, GeneratedExport } from '../types';
import { PathResolver } from '../utils/pathResolver';

export class PHPGenerator {
  private pathResolver: PathResolver;

  constructor(pathResolver: PathResolver) {
    this.pathResolver = pathResolver;
  }

  generate(view: ViewConfig): GeneratedExport {
    const content = this.buildPHPDocument(view);

    return {
      format: 'php',
      content,
      filename: `${this.sanitizeFilename(view.name)}.php`
    };
  }

  private buildPHPDocument(view: ViewConfig): string {
    const phpHelpers = this.generatePHPHelpers();
    const html = this.generateNodePHP(view.root, 0);
    const css = this.generateCSS(view);
    const js = this.generateJS(view);

    return `<?php
/**
 * NexusGPro Generated View
 * View: ${view.name}
 * Description: ${view.description || 'N/A'}
 * Generated: ${new Date().toISOString()}
 * Version: ${view.metadata.version}
 */

${phpHelpers}

// View Configuration
$view_config = [
  'name' => '${view.name}',
  'version' => '${view.metadata.version}',
  'created' => '${view.metadata.created}',
  'updated' => '${view.metadata.updated}'
];

// Check if this is an API request
if (isset($_GET['api']) || isset($_POST['api'])) {
  header('Content-Type: application/json');
  handleApiRequest();
  exit;
}

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  handleFormSubmit();
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo htmlspecialchars($view_config['name']); ?> - NexusGPro</title>
  <meta name="description" content="<?php echo htmlspecialchars('${view.description || 'Generated with NexusGPro Builder'}'); ?>">
  <meta name="generator" content="NexusGPro Builder v<?php echo $view_config['version']; ?>">

  <style>
${css}
  </style>
</head>
<body>
  <!-- Generated by NexusGPro Builder -->
  <!-- View: <?php echo $view_config['name']; ?> -->
  <!-- Updated: <?php echo $view_config['updated']; ?> -->

<?php
// PHP-generated content
${html}
?>

  <script>
${js}
  </script>
</body>
</html>

<?php
// API Request Handler
function handleApiRequest() {
  $method = $_SERVER['REQUEST_METHOD'];
  $action = $_GET['action'] ?? $_POST['action'] ?? 'default';

  switch ($action) {
    case 'getData':
      echo json_encode([
        'success' => true,
        'data' => [],
        'message' => 'Data retrieved successfully'
      ]);
      break;

    case 'saveData':
      $input = json_decode(file_get_contents('php://input'), true);
      echo json_encode([
        'success' => true,
        'message' => 'Data saved successfully'
      ]);
      break;

    default:
      http_response_code(400);
      echo json_encode([
        'success' => false,
        'error' => 'Invalid action'
      ]);
  }
}

// Form Submit Handler
function handleFormSubmit() {
  // Process form data here
  $data = $_POST;

  // Validate and sanitize
  foreach ($data as $key => $value) {
    $data[$key] = htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
  }

  // Add your processing logic here
  // Example: Database operations, email sending, etc.
}
?>`;
  }

  private generatePHPHelpers(): string {
    return `
// NexusGPro PHP Helpers
function renderComponent($type, $props = [], $children = '') {
  $id = $props['id'] ?? uniqid('comp_');
  $class = $props['className'] ?? '';
  $style = isset($props['styles']) ? styleArrayToString($props['styles']) : '';

  return renderComponentHTML($type, $id, $class, $style, $props, $children);
}

function renderComponentHTML($type, $id, $class, $style, $props, $children) {
  $attrs = "id='$id' class='$class' style='$style' data-component='$type'";

  switch ($type) {
    case 'Button':
      $variant = $props['variant'] ?? 'primary';
      $size = $props['size'] ?? 'md';
      $disabled = isset($props['disabled']) && $props['disabled'] ? 'disabled' : '';
      return "<button $attrs data-variant='$variant' data-size='$size' $disabled>$children</button>";

    case 'Input':
      $type_attr = $props['type'] ?? 'text';
      $placeholder = $props['placeholder'] ?? '';
      $value = $props['value'] ?? '';
      $disabled = isset($props['disabled']) && $props['disabled'] ? 'disabled' : '';
      return "<input $attrs type='$type_attr' placeholder='$placeholder' value='$value' $disabled />";

    case 'Card':
      return "<div $attrs>$children</div>";

    case 'Modal':
      $isOpen = isset($props['isOpen']) && $props['isOpen'] ? 'block' : 'none';
      return "<div $attrs style='display: $isOpen;'>$children</div>";

    default:
      return "<div $attrs>$children</div>";
  }
}

function styleArrayToString($styles) {
  if (!is_array($styles)) return '';
  $result = [];
  foreach ($styles as $key => $value) {
    $key = camelToKebab($key);
    $result[] = "$key: $value";
  }
  return implode('; ', $result);
}

function camelToKebab($str) {
  return strtolower(preg_replace('/([a-z0-9])([A-Z])/', '$1-$2', $str));
}

function escapeHtml($text) {
  return htmlspecialchars($text, ENT_QUOTES, 'UTF-8');
}
`;
  }

  private generateNodePHP(node: ComponentNode, depth: number): string {
    const indent = '  '.repeat(depth);

    const propsArray = this.generatePHPPropsArray(node);
    const children = this.generateChildrenPHP(node, depth);

    return `${indent}echo renderComponent('${node.name}', ${propsArray}, ${children});`;
  }

  private generatePHPPropsArray(node: ComponentNode): string {
    const props: string[] = [];

    props.push(`'id' => '${node.id}'`);

    if (node.className) {
      props.push(`'className' => '${node.className}'`);
    }

    if (node.styles) {
      const styleEntries = Object.entries(node.styles)
        .map(([key, value]) => `'${key}' => '${value}'`)
        .join(', ');
      props.push(`'styles' => [${styleEntries}]`);
    }

    Object.entries(node.props).forEach(([key, value]) => {
      if (key === 'children') return;

      if (typeof value === 'string') {
        props.push(`'${key}' => '${value.replace(/'/g, "\\'")}'`);
      } else if (typeof value === 'boolean') {
        props.push(`'${key}' => ${value ? 'true' : 'false'}`);
      } else if (typeof value === 'number') {
        props.push(`'${key}' => ${value}`);
      } else if (Array.isArray(value)) {
        props.push(`'${key}' => ${JSON.stringify(value)}`);
      } else if (typeof value === 'object' && value !== null) {
        props.push(`'${key}' => ${JSON.stringify(value)}`);
      }
    });

    return `[${props.join(', ')}]`;
  }

  private generateChildrenPHP(node: ComponentNode, depth: number): string {
    if (node.children && node.children.length > 0) {
      const childrenCode = node.children
        .map(child => this.generateNodePHP(child, depth + 1))
        .join('\n');
      return `"\n${childrenCode}\n"`;
    } else if (node.props.children) {
      return `'${String(node.props.children).replace(/'/g, "\\'")}'`;
    }
    return "''";
  }

  private generateCSS(view: ViewConfig): string {
    return `/* NexusGPro Generated Styles - PHP Version */
/* View: ${view.name} */
/* Generated: ${new Date().toISOString()} */

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.6;
  color: #333;
}

[data-component] {
  box-sizing: border-box;
}

button[data-component="Button"] {
  cursor: pointer;
  padding: 0.5rem 1rem;
  border-radius: 0.375rem;
  border: none;
  font-weight: 500;
  transition: all 0.2s;
}

button[data-variant="primary"] {
  background: #3b82f6;
  color: white;
}

button[data-variant="secondary"] {
  background: #6b7280;
  color: white;
}

button[data-variant="outline"] {
  background: transparent;
  border: 2px solid #3b82f6;
  color: #3b82f6;
}

button:hover {
  opacity: 0.9;
  transform: translateY(-1px);
}

button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

[data-component="Card"] {
  background: white;
  border-radius: 0.5rem;
  padding: 1.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

[data-component="Input"] {
  padding: 0.5rem 0.75rem;
  border: 1px solid #d1d5db;
  border-radius: 0.375rem;
  font-size: 1rem;
  width: 100%;
}

[data-component="Input"]:focus {
  outline: none;
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

[data-component="Modal"] {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}
`;
  }

  private generateJS(view: ViewConfig): string {
    return `// NexusGPro Generated JavaScript - PHP Version
// View: ${view.name}
// Generated: ${new Date().toISOString()}

document.addEventListener('DOMContentLoaded', function() {
  console.log('View loaded: ${view.name}');
  initializeComponents();
});

function initializeComponents() {
  // Button click handlers
  document.querySelectorAll('button[data-component="Button"]').forEach(button => {
    button.addEventListener('click', function(e) {
      console.log('Button clicked:', this.id);
    });
  });

  // Input handlers
  document.querySelectorAll('input[data-component="Input"]').forEach(input => {
    input.addEventListener('change', function(e) {
      console.log('Input changed:', this.id, this.value);
    });
  });

  // Modal handlers
  document.querySelectorAll('[data-component="Modal"]').forEach(modal => {
    const closeBtn = modal.querySelector('[data-action="close"]');
    if (closeBtn) {
      closeBtn.addEventListener('click', () => {
        modal.style.display = 'none';
      });
    }
  });
}

// PHP API Communication
async function phpApiCall(action, data = null, method = 'POST') {
  const formData = new FormData();
  formData.append('api', '1');
  formData.append('action', action);

  if (data) {
    Object.keys(data).forEach(key => {
      formData.append(key, data[key]);
    });
  }

  try {
    const response = await fetch(window.location.href, {
      method: method,
      body: formData
    });
    return await response.json();
  } catch (error) {
    console.error('API call failed:', error);
    throw error;
  }
}

// Form submission helper
function handleFormSubmit(formId, callback) {
  const form = document.getElementById(formId);
  if (!form) return;

  form.addEventListener('submit', async function(e) {
    e.preventDefault();
    const formData = new FormData(form);

    try {
      const response = await fetch(window.location.href, {
        method: 'POST',
        body: formData
      });

      if (response.ok) {
        if (callback) callback(await response.json());
      }
    } catch (error) {
      console.error('Form submission failed:', error);
    }
  });
}

window.NexusGProPHP = {
  apiCall: phpApiCall,
  handleFormSubmit,
  viewName: '${view.name}'
};
`;
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
  }
}
